services:
  db:
    container_name: pangya_db
    hostname: pangya_db
    ports:
      - "5432:5432"
    image: postgres
    volumes:
      - ./psql:/var/lib/postgresql:z
      - ./dbinit:/docker-entrypoint-initdb.d/:z
      - ./schema:/opt/bk-squema:z
    environment:
      POSTGRES_PASSWORD: "pangya123"
      POSTGRES_HOST_AUTH_METHOD: "md5"
      POSTGRES_INITDB_ARGS: "--auth=md5 --auth-host=md5 --locale=en_US.UTF-8 --encoding=UTF-8"
    networks:
      - pangya

  app:
    container_name: pangya_app
    hostname: pangya_app
    ports:
      - "7777:7777"
      - "20203:20203"
      - "10303:10303"
      - "30303:30303"
      - "4774:4774"
    image: japangya
    build: .
    restart: "on-failure"
    depends_on:
      - db
    networks:
      - pangya
    volumes:
      - "./ini/auth_server.ini:/opt/Auth Server/server.ini"
      - "./ini/game_server.ini:/opt/Game Server/server.ini"
      - "./ini/login_server.ini:/opt/Login Server/server.ini"
      - "./ini/message_server.ini:/opt/Message Server/server.ini"
      - "./ini/rank_server.ini:/opt/Rank Server/server.ini"
      - "./pangya_jp.iff:/opt/Game Server/data/pangya_jp.iff"
      - "./discord-config.json:/opt/Smart-Calculator/Discord/config.json"
      - www:/www
    command: /bin/bash -c "while true; do sleep 10; done"

  web:
    container_name: web
    hostname: web
    image: nginx
    networks:
      - pangya
    volumes:
      - ./www:/usr/share/nginx/html:z
      - "./updatelist:/usr/share/nginx/html/S4_Patch/updatelist:z"
    ports:
      - "8080:80"

volumes:
  www:
  dbinit:

networks:
  pangya:
    name: pangya-network
